#!/bin/bash
 
sudo apt purge --ignore-missing -y \
irqbalance \
geary \
firefox \
firefox-locale-ar \
firefox-locale-en \
firefox-locale-fr \
firefox-locale-ja \
firefox-locale-ru \
firefox-locale-zh-hant \
firefox-locale-de \
firefox-locale-es \
firefox-locale-it \
firefox-locale-pt \
firefox-locale-zh-hans \
gnome-contacts \
gnome-calendar \
gnome-calculator \
gnome-getting-started-docs \
gnome-getting-started-docs-de \
gnome-getting-started-docs-es \
gnome-getting-started-docs-fr \
gnome-getting-started-docs-it \
gnome-getting-started-docs-ja \
gnome-getting-started-docs-pt \
gnome-getting-started-docs-ru \
gnome-getting-started-docs-zh-hk \
gnome-getting-started-docs-zh-tw \
gnome-user-docs \
gnome-user-docs-de \
gnome-user-docs-es \
gnome-user-docs-fr \
gnome-user-docs-it \
gnome-user-docs-ja \
gnome-user-docs-pt \
gnome-user-docs-ru \
gnome-user-docs-zh-hans \
libreoffice-style-colibre \
libreoffice-style-elementary \
libreoffice-style-tango \
libreoffice-gnome \
libreoffice-writer \
libreoffice-calc \
libreoffice-impress \
libreoffice-math \
libreoffice-l10n-en-gb \
libreoffice-l10n-es \
libreoffice-l10n-zh-cn \
libreoffice-l10n-zh-tw \
libreoffice-l10n-pt \
libreoffice-l10n-pt-br \
libreoffice-l10n-de \
libreoffice-l10n-fr \
libreoffice-l10n-it \
libreoffice-l10n-ru \
libreoffice-l10n-en-za \
libreoffice-help-en-gb \
libreoffice-help-es \
libreoffice-help-zh-cn \
libreoffice-help-zh-tw \
libreoffice-help-pt \
libreoffice-help-pt-br \
libreoffice-help-de \
libreoffice-help-fr \
libreoffice-help-it \
libreoffice-help-ru \
libreoffice-help-en-us \
hunspell-ar \
hunspell-de-at-frami \
hunspell-de-ch-frami \
hunspell-de-de-frami \
hunspell-en-au \
hunspell-en-ca \
hunspell-en-us  \
hunspell-en-za \
hunspell-es \
hunspell-fr \
hunspell-fr-classical \
hunspell-it \
hunspell-pt-br \
hunspell-pt-pt \
hunspell-ru \
hyphen-de \
hyphen-en-ca \
hyphen-en-us \
hyphen-es \
hyphen-fr \
hyphen-hr \
hyphen-it \
hyphen-pl \
hyphen-pt-br \
hyphen-pt-pt \
hyphen-ru \
mythes-de \
mythes-de-ch \
mythes-en-au \
mythes-en-us \
mythes-fr \
mythes-it \
mythes-pt-pt \
mythes-ru \
gir1.2-totem-1.0 \
gir1.2-totemplparser-1.0 \
simple-scan \
baobab \
totem \
totem-common \
totem-plugins \
libtotem0 \
language-pack-ar \
language-pack-ar-base \
language-pack-de \
language-pack-de-base \
language-pack-es \
language-pack-es-base \
language-pack-fr \
language-pack-fr-base \
language-pack-gnome-ar \
language-pack-gnome-ar-base \
language-pack-gnome-de \
language-pack-gnome-de-base \
language-pack-gnome-es \
language-pack-gnome-es-base \
language-pack-gnome-fr \
language-pack-gnome-fr-base \
language-pack-gnome-it \
language-pack-gnome-it-base \
language-pack-gnome-ja \
language-pack-gnome-ja-base \
language-pack-gnome-pt \
language-pack-gnome-pt-base \
language-pack-gnome-ru \
language-pack-gnome-ru-base \
language-pack-gnome-zh-hans \
language-pack-gnome-zh-hans-base \
language-pack-gnome-zh-hant \
language-pack-gnome-zh-hant-base \
language-pack-it \
language-pack-it-base \
language-pack-ja \
language-pack-ja-base \
language-pack-pt \
language-pack-pt-base \
language-pack-ru \
language-pack-ru-base \
language-pack-zh-hans \
language-pack-zh-hans-base \
language-pack-zh-hant \
language-pack-zh-hant-base \
mobile-broadband-provider-info \
wamerican \
wbrazilian \
wfrench \
wportuguese \
wspanish \
wswiss \
&& sudo apt autoremove -y && sudo apt autoclean
