#!/bin/bash
 
sudo apt install --install-recommends -y \
preload \
locate \
htop \
neofetch \
vim \
fonts-powerline \
powerline \
zsh \
zsh-autosuggestions \
zsh-syntax-highlighting \
gnome-tweak-tool \
ubuntu-restricted-extras \
ubuntu-restricted-addons \
alacritty \
flameshot \
fonts-roboto \
qt5-style-plugins \
materia-gtk-theme \
papirus-icon-theme \
breeze-cursor-theme \
nfs-common \
pavucontrol \
autokey-gtk \
autokey-common \
ckb-next \
lxappearance \
system76-cuda-latest \
nvidia-cuda-toolkit \
gimp \
blender \
audacity \
lollypop \
filezilla \
fonts-cantarell \
fonts-hack \
fonts-hack-otf \
fonts-hack-ttf \
fonts-hack-web \
fonts-noto \
fonts-font-awesome \
fonts-lmodern \
ttf-ubuntu-font-family \
cmatrix \
cmatrix-xfont \
lolcat \
cowsay-off \
fortunes \
fortune-mod \
rsync \
faac \
flac \
libdca-utils \
x264 \
x265 && sudo /lib/systemd/systemd-sysv-install enable preload